### ISSUE TITLE
Change to horizontal layout

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/io-honerlaw-modules#16]
Derek,

See the attached image, it shows what I think we should do.
![amazon](https://cloud.githubusercontent.com/assets/22616163/19460910/38bb8132-94ae-11e6-8be2-e85f5636af32.PNG)

**Comment by honerlaw** [comment]
I ended up moving it in line with the add to cart stuff so it flows more with the current layout of amazon.
<img width="1676" alt="screen shot 2016-10-26 at 9 03 32 pm" src="https://cloud.githubusercontent.com/assets/2515033/19750518/c1a2ae68-9bbf-11e6-92e3-fe50944216f3.png">
