### ISSUE TITLE
Add More Alerts

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/io-honerlaw-modules#17]
I was thinking we should add a few more alerts on things I think people will want to know especially around the holiday season.....

I think they should be alerted when:
- Item Goes On Sale (don't know if this one can be done, but if there are items with a percentage off then that would be a good one to add)
- Item Price Drops (a bit different, because whether it drops a penny or ten dollars it alerts them)
- Item Quantity Decreases Below..(enter value)
- Free Shipping is Available
- Amazon Prime is Available

I think some of these were on the original mock-up, but let me know which ones are feasible in the little amount of time we have. (remember, Black Friday & Cyber Monday are right around the corner so we gotta get as much done so we can focus on getting users and have this pay off, AND IT WILL as long as we push hard to get this done)

So let me know what you think.

Thanks Partna!

**Comment by honerlaw** [comment]
I added item price drops...

However, the rest could be harder to implement (It looks like the API might not give us quantity, prime eligibility, or free shipping). This specifically affects

* Free Shipping
* Amazon Prime
* Item Quantity Change (increase / decrease)

For the `Item Goes On Sale`, a percentage off would be similar to the price dropping (basically we just need to check if the price changes by a set percentage as you suggested).
