### ISSUE TITLE
Alert Me Extension Issues

### ISSUE THREAD

**Issue by OnlineEmpireInc** [honerlaw/io-honerlaw-modules#20]
Hey Derek,

I uploaded the extension and while testing I kept getting "Failed to start watching for price changes. Please try again." at the top of the extension form (see attached)

I also tried to "Go To" Alert Me, through the use of the button, but it only directs me to a 502 Bad Gateway page. Actually I think we should make it say "Alert Me Members Area"

I also tried to go to alertmemembers.com to see if you just hadn't changed the link yet, but that doesn't seem to be working either.

When you get a second, can you look into these for me? I know it's you're birthday, so I'll give you a break this time!!! :)

Alright man, well give me a shout when you get all this figured out.

Thanks and talk soon!
![issue 2](https://cloud.githubusercontent.com/assets/22616163/20082115/d90fc6a6-a521-11e6-8d12-eebdbc289258.png)
![issue 1](https://cloud.githubusercontent.com/assets/22616163/20082116/d914eba4-a521-11e6-8bbc-3a8baa439270.png)

**Comment by honerlaw** [comment]
Server is back up and running
